### ISSUE TITLE
Token refresh failed

### ISSUE THREAD

**Issue by Beat540** [AdyRock/com.mercedes_me#2]
Hi Adrian
I get the error message "Token refresh failed"
Thank you for your help

**Comment by AdyRock** [comment]
Is it the first time you have logged in or has the app been running for a while?

**Comment by Beat540** [comment]
This is the first time I am signing up with this setting.  Had signed up before but token was wrong

***@***.***


Am 08.11.2021 um 22:43 schrieb Adrian Rockall ***@***.***>:

Is it the first time you have logged in or has the app been running for a while?

**Comment by AdyRock** [comment]
OK, so I guess you have entered the settings in the Configure App page?
At what point do you see the error?

**Comment by Beat540** [comment]
Hi Adrian, the second time it worked.  thanks

Mit freundlichen Grüssen

Beat Ineichen
ineichen.online gmbh
Oberstadt 10
6204 Sempach

***@***.***
+41 794327161

Am 08.11.2021 um 23:41 schrieb Adrian Rockall ***@***.***>:

﻿

OK, so I guess you have entered the settings in the Configure App page?
At what point do you see the error?

**Comment by AdyRock** [comment]
That's good to hear. It's a shame they make it so difficult.
